// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VoyadoSearch.Persistence;

namespace VoyadoSearch.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20201213215341_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.1");

            modelBuilder.Entity("VoyadoSearch.Persistence.Abstract.Entities.SearchCache", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("Created")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("EngineId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<long>("Hits")
                        .HasColumnType("bigint");

                    b.Property<string>("Term")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTimeOffset?>("Updated")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("Created")
                        .HasDatabaseName("IX_SearchCache_Created");

                    b.HasIndex("EngineId")
                        .HasDatabaseName("IX_SearchCache_EngineId");

                    b.HasIndex("Term")
                        .HasDatabaseName("IX_SearchCache_Term")
                        .HasFilter("[Term] IS NOT NULL");

                    b.ToTable("Search", "cache");
                });

            modelBuilder.Entity("VoyadoSearch.Persistence.Abstract.Entities.SearchHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("Created")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Term")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("Updated")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.ToTable("History", "search");
                });
#pragma warning restore 612, 618
        }
    }
}
